Домашнее задание 11
kgamora/formal-lang-course pull request #10
Opened 2023-05-16 00:51 UTC by kgamora

Забыл создать пр (а ещё тесты в процессе написания...)
10 домашку дошлю тоже - решил сразу писать конкретный синтаксис, выраженный правилами антлра

2023-05-22 08:08 UTC, rustam-azimov requested changes
Жду тестов

2023-06-06 18:09 UTC, kgamora commented
Добавил тесты для 11 задания. Настроил тестирование, 11 задание тесты проходит (на остальные сейчас посмотрю, попробую их тоже заставить работать)

2023-06-06 18:32 UTC, kgamora commented
превосходно, теперь всё ещё и зелёненькое. В общем, как я и говорил выше, это не только парсер, но и описание языка (т.е. прошлая домашка) в виде парсера (ну и в README тоже есть описание)

2023-06-18 16:36 UTC, rustam-azimov approved these changes
Вы конечно поздно прислали, но половину баллов сниму только за 10ую.

2023-06-20 14:25 UTC, merged