Task 6, Гамора Константин
kgamora/formal-lang-course pull request #4
Opened 2023-04-02 00:13 UTC by kgamora

2023-04-02 08:42 UTC, rustam-azimov requested changes

2023-04-02 08:42 UTC, rustam-azimov commented on project/task_06/source.py
> +        grammar.remove_useless_symbols()
Можно без этой строчки

2023-04-02 20:06 UTC, kgamora commented on project/task_06/source.py
> +        grammar.remove_useless_symbols()
поправил

2023-04-07 13:27 UTC, rustam-azimov approved these changes

2023-04-15 21:26 UTC, merged